### ISSUE TITLE
Clean up landing page markup

### ISSUE THREAD

**Issue by geoffreylitt** [codeforboston/mbta-ninja#117]
The landing page should be powered by a cleaner javascript data structure, not a bunch of redundant HTML.

**Comment by geoffreylitt** [comment]
Thank you @davidlago! This is awesome.

**Comment by davidlago** [comment]
Good call @geoffreylitt opening this issue... it was getting out of control :)
There are still some places that are "ripe for refactoring", but this was probably the biggest one.
