### ISSUE TITLE
Missing link in Readme file

### ISSUE THREAD

**Issue by Shanfan** [codeforboston/mbta-ninja#146]
Missing a guide link:
![image](https://cloud.githubusercontent.com/assets/869370/10458704/1c5bf48c-719a-11e5-9df3-1a485b1ba6d1.png)

**Comment by davidlago** [comment]
The guide is what follows that intro header, not a separate document.

**Comment by JacobEvelyn** [comment]
@davidlago it might be better to re-word that to avoid future confusion.

**Comment by davidlago** [comment]
Updated :)

**Comment by Shanfan** [comment]
Haha yeah I figured so. Thanks for updating. While I was following the instructions, I also added some missing info to the README.md that helped me to successfully deploy the app. I just created a pull request. Please take a look. Hope it helps.
