### ISSUE TITLE
Add support for orange line

### ISSUE THREAD

**Issue by radhikamalik** [codeforboston/mbta-ninja#19]
A lot of popular demand!

**Comment by patrickgreenwell** [comment]
I'd morph this into consuming [GTFS data](https://developers.google.com/transit/gtfs/reference) about subway stops and listing them out as separate lines.

Take a look at [routes.txt](https://developers.google.com/transit/gtfs/reference#routes_fields)

you could filter the list of stuff there based on the route_type.

You'd probably need to modify how you load up stops in Mongo to make it different than the static list you have now.

**Comment by geoffreylitt** [comment]
Thanks for the tip @patrickgreenwell ! I'm going to look into that now for adding all the MBTA lines.

**Comment by patrickgreenwell** [comment]
there's also a node-gtfs tool that loads a gtfs feed into a mongo db [brendannee/node-gtfs](https://github.com/brendannee/node-gtfs) I believe.

**Comment by geoffreylitt** [comment]
Awesome, that's a really helpful tip @patrickgreenwell ! Thanks so much.

I played around with the API for a bit, but decided to quickly hack in green/orange line support for tomorrow morning. Will look into a more sustainable approach w/ the API as part of #13 .
