### ISSUE TITLE
Expire old events from the page

### ISSUE THREAD

**Issue by geoffreylitt** [codeforboston/mbta-ninja#2]
I think the right strategy is just to delete any events that were last confirmed more than X minutes ago. X can probably be something like 30 min to an hour.

(Right now we only have a `createdAt` timestamp on an event, but we should add a `lastConfirmed`)

**Comment by davidlago** [comment]
The event purge by TTL doesn't work in hosted mongo (MongoLab)... we need to investigate why. It works properly when running in local meteor.
