### ISSUE TITLE
Add back "normal conditions" in some way?

### ISSUE THREAD

**Issue by geoffreylitt** [codeforboston/mbta-ninja#35]
I think this becomes more useful if people can actively report normal conditions rather than just clearing alerts. It becomes a tool that can reassure in addition to warm -- similar to how in the text group, people report "everything was fine."

Also, if someone first opens the app and conditions are normal, they're able to interact and do something, which probably increases their chances of future usage.

@radhikamalik what was your thought on removing this? did you disagree with having this at all, or did you just want to think it through a bit more?

**Comment by radhikamalik** [comment]
Hmm, agree on the engagement part and that we need some way of reporting
all is ok. I think in its previous form it just needed a bit more thinking
through with its interaction with the all clear ninja, the all clear button
and what it means to have a reported incident and a reported all ok both at
the same time. I would not be opposed to putting it back in if we think
through it a little.

**Comment by radhikamalik** [comment]
I'm adding this back in and adding a separate issue to resolve interactions with other elements.

**Comment by radhikamalik** [comment]
#38 opened as follow up
