### ISSUE TITLE
Add an official twitter account?

### ISSUE THREAD

**Issue by geoffreylitt** [codeforboston/mbta-ninja#36]
If we tweeted out confirmed alerts from an MBTA Ninja twitter, that could raise a lot of awareness. (More than just constantly tweeting "use MBTA Ninja!")

We could also just try to integrate with the MBTA Alerts twitter as discussed yesterday.

Or we could do both.

**Comment by radhikamalik** [comment]
We should probably do both.

Added our account. Credentials to be shared in person :)

https://twitter.com/mbta_ninja
