### ISSUE TITLE
Resolve interaction of "Normal Conditions" with other elements

### ISSUE THREAD

**Issue by radhikamalik** [codeforboston/mbta-ninja#38]
- All clear button
- All clear ninja
- Other incidents reported in the same station

**Comment by radhikamalik** [comment]
Also maybe have a big plus in green to add those (instead of the regular report incident button)

**Comment by davidlago** [comment]
Somehow related to #18 too?

**Comment by davidlago** [comment]
Closing this, addressed with new decay feature. We can open up new issues to tweak it if we need to.
