### ISSUE TITLE
Logo filesize can be smaller

### ISSUE THREAD

**Issue by JacobEvelyn** [codeforboston/mbta-ninja#39]

**Comment by radhikamalik** [comment]
what do you mean by the logo is gigantic @JacobEvelyn ?

**Comment by radhikamalik** [comment]
@JacobEvelyn ready to close?

**Comment by JacobEvelyn** [comment]
I'd rather keep this open since there are further optimizations to be made (eliminating white area, and reducing further once #64 merges).

**Comment by davidlago** [comment]
I'm closing this since the logo seems small enough with no whitespace around and good to go... I don't think it's an issue anymore. That said, @JacobEvelyn feel free to send new PRs to further improve it if you want to.
