### ISSUE TITLE
Green Line Termination 

### ISSUE THREAD

**Issue by bjohn249** [codeforboston/mbta-ninja#56]
Awesome with green line addition. E branch terminates at Lechmere and B branch terminates at Park street however.

**Comment by radhikamalik** [comment]
Thanks for the issue @bjohn249. I believe https://github.com/davidlago/mbta-ninja/pull/68 fixed this?

**Comment by davidlago** [comment]
Yes @radhikamalik, I checked and the terminations are correct now.
