### ISSUE TITLE
"Report Issue" button goes below on narrow screens

### ISSUE THREAD

**Issue by radhikamalik** [codeforboston/mbta-ninja#70]
I had tested on iPhone 6 but so it works ok there but goes below on iPhone 4/5 i.e. the narrower screens.

![screen shot 2015-02-25 at 9 17 42 pm](https://cloud.githubusercontent.com/assets/3731787/6385108/c3c75f0c-bd33-11e4-9494-bc48d85d9133.png)

**Comment by geoffreylitt** [comment]
Changing the button text to "report" to fix this.
