### ISSUE TITLE
Add commuter rail lines

### ISSUE THREAD

**Issue by susanzellmannrohrer** [codeforboston/mbta-ninja#75]

**Comment by geoffreylitt** [comment]
Thanks for the feature request! We've heard this from a lot of people and will get around to adding them ASAP.

**Comment by geoffreylitt** [comment]
Based on the size of the commuter rail lines, I would recommend that we switch to getting routes from the MBTA GTFS API rather than hardcoding these in.

I'm going to play with https://github.com/brendannee/node-gtfs to see if we can do this.

**Comment by nchammas** [comment]
+1 for this. Would be great to have!
