### ISSUE TITLE
Consolidate In/Out/bound traffic to one page

### ISSUE THREAD

**Issue by mnolan2** [codeforboston/mbta-ninja#83]
Right now we're split between two different pages for each direction of traffic. Can you merge the two pages together, showing two parallel tracks with traffic notices/indications on either side? It'd be nice to see all of the information for a given line at once.

**Comment by deverstalmage** [comment]
+1 for this, I had this exact same thought when I was working on it this morning. Some arrows would probably be very useful in the design

**Comment by mnolan2** [comment]
Less of a big deal for me, but could you also scale the display to the size of the screen that you're using? For example, even with the bidirectional display that @deverstalmage and I proposed above, the tracks might look better at the center of the window. This would also work out well for mobile users, so that scrolling would only be necessary in the up/down direction.

this is the current display:

![current_display](https://cloud.githubusercontent.com/assets/4379362/6400718/fa1a8030-bdc8-11e4-82c4-b7b3f5b197cb.png)

and this is a very, very bad implementation (thanx paint) of what I'm thinking (arrows to show direction, should be replaced by a nice North/South or something more creative)

![proposed_display](https://cloud.githubusercontent.com/assets/4379362/6400744/21e915a4-bdc9-11e4-8538-4134e214db78.png)

**Comment by geoffreylitt** [comment]
Thanks for the suggestions! Great to see community input on this project :)

Right now, the site is 100% optimized for mobile, and we haven't thought much about the desktop experience yet. I think the core team is going to continue focusing on mobile for the near future, which wouldn't putting include the line in the center of the screen -- but I agree that that view would totally make sense for wider screens. If you want to submit a PR to add that, I think it would be a good improvement for desktop users.

As far as merging northbound and southbound in one view on a mobile screen, we debated doing that originally but thought it might be clearer to separate out the directions. Do commuters going southbound really care about northbound alerts? My tentative answer is, not really, unless they impact the southbound experience, in which case I should get alerts about that directly. Would be curious to hear your thoughts on what the use case is @mnolan2 @deverstalmage

**Comment by mnolan2** [comment]
Having fewer links from the main screen seems like a benefit to me.

As far as southbounders caring for the hardships of northbounders goes, I'm not certain. Some stops have shared platforms; having some knowledge of imminent crowds might be nice.

**Comment by davidlago** [comment]
I agree with @geoffreylitt in that we should not design for desktop computers... It should work, and it shouldn't look ugly, but that is as far as I'd get, at least for now.

As for the two directions in the same page, it gets very complicated in a phone screen, especially if you want to keep them side by side. This sounds like an interesting UI/UX challenge! :)

It is true though that it would be great to reduce the amount of real-estate used by the list of lines... and I'm happy to explore options. Maybe the line button when pressed reveals the NB/SB options and after a second click/tap it takes you to the right page? Maybe the ability to switch between NB and SB by clicking the title bar? (i.e. if I'm seeing the Red Line Northbound, and click on the word Northbound it takes me to the Southbound version).

**Comment by deverstalmage** [comment]
I like the idea of revealing the NB/SB options on tap, and combined with the swapping NB/SB on title bar tap I think it could work nicely. Collapsible in Materialize would work well http://materializecss.com/collapsible.html

Would it make sense to reverse the order of the stations on each direction? e.g. Northbound Red has Alewife at the top, while Southbound Red has Ashmont at the top?

**Comment by deverstalmage** [comment]
created a PR for combining the nb/sb lines: https://github.com/davidlago/mbta-ninja/pull/94
